version: "3"
services:
  # app:
  #   image: node:10
  #   command: ["node"]
  #   env_file: $PWD/../key/docker/docker.env
  #   networks:
  #     - redis-net
  #   depends_on:
  #     - redis
  redis:
    image: redis:4.0.5-alpine
    env_file: $PWD/../key/docker/docker.env
    command: sh -c 'redis-server --appendonly yes --requirepass $$PASSWORD'
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - redis-net
    volumes:
      - $PWD/redis/data:/data
networks:
  redis-net:
